# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokey < Formula
  desc "A powerful CLI tool for managing Lokey operations"
  homepage "https://github.com/ThywillJoshua/lokey-cli"
  version "0.17"

  depends_on "go"

  on_macos do
    url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.17/lokey-cli_0.17_darwin_all.tar.gz"
    sha256 "bf5f9b92250140dd70f18edfae440973b82a8786912740a6381b0810dc14c863"

    def install
      bin.install "lokey-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.17/lokey-cli_0.17_linux_amd64.tar.gz"
        sha256 "e07f7769ce142467715c2d479517ccc003bc847d2a783a5edf6edc85afa9ccc5"

        def install
          bin.install "lokey-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.17/lokey-cli_0.17_linux_arm64.tar.gz"
        sha256 "bb4e884bbe91aaa8428b00bde6bbda76c4c5b9d523db4eb428acd4ebbb415b4b"

        def install
          bin.install "lokey-cli"
        end
      end
    end
  end
end
