# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokey < Formula
  desc "A powerful CLI tool for managing Lokey operations"
  homepage "https://github.com/ThywillJoshua/lokey-cli"
  version "0.12"

  depends_on "go"

  on_macos do
    url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.12/lokey-cli_0.12_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "ad618aef480bf7ae27560b3e84bb318a7ac8a04525f86caab765cd3ebc1610ed"

    def install
      bin.install "lokey"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.12/lokey-cli_0.12_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "0f2784bf47c7fb6d5c92c1eef1a453a08cd1e377edb32f9acbd920e7b95da42d"

        def install
          bin.install "lokey"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.12/lokey-cli_0.12_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "336613a7eeec3175b7762b9f982259731a6267544b4749bed6270db456e94e36"

        def install
          bin.install "lokey"
        end
      end
    end
  end
end
