# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokey < Formula
  desc "A powerful CLI tool for managing Lokey operations"
  homepage "https://github.com/ThywillJoshua/lokey-cli"
  version "0.16"

  depends_on "go"

  on_macos do
    url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.16/lokey-cli_0.16_darwin_all.tar.gz"
    sha256 "7d0abb054c943719cb84616ddcda1cde99c0d33e058cc0ed2a4b14a2ba17f7b6"

    def install
      bin.install Dir["*"].find { |f| File.basename(f) == "lokey" }
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.16/lokey-cli_0.16_linux_amd64.tar.gz"
        sha256 "c26c9834dec7206efea5cf6dae2b72838e170999be2eabd95712cd8507e30161"

        def install
          bin.install Dir["*"].find { |f| File.basename(f) == "lokey" }
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.16/lokey-cli_0.16_linux_arm64.tar.gz"
        sha256 "0b550676c10d0d05fe828a7592b433600085e47ccfa1572ca5d3637b4929d0cc"

        def install
          bin.install Dir["*"].find { |f| File.basename(f) == "lokey" }
        end
      end
    end
  end
end
